# Chart.yaml
apiVersion: v2
name: amqp-demo
description: Minimal AMQP client with RabbitMQ
version: 0.1.0
appVersion: "1.0"

---
# values.yaml
rabbitmq:
  image: rabbitmq:3-management
  user: guest
  password: guest

amqpClient:
  image: amqp-client:latest
  host: rabbitmq-service
  port: 5672
  user: guest
  password: guest
  vhost: /
  exchange: test_exchange
  topic: test.key
  queue: test_queue
  sendCount: 1000
  receiveCount: 1000

---
# templates/rabbitmq.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image }}
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.user }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmq.password }}
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "ping"]
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672

---
# templates/amqp-client.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amqp-client
  template:
    metadata:
      labels:
        app: amqp-client
    spec:
      containers:
      - name: amqp-client
        image: {{ .Values.amqpClient.image }}
        command:
        - sh
        - -c
        - "./start_amqp.sh both"
        env:
        - name: AMQP_HOST
          value: {{ .Values.amqpClient.host }}
        - name: AMQP_PORT
          value: "{{ .Values.amqpClient.port }}"
        - name: AMQP_USER
          value: {{ .Values.amqpClient.user }}
        - name: AMQP_PASSWORD
          value: {{ .Values.amqpClient.password }}
        - name: AMQP_VHOST
          value: {{ .Values.amqpClient.vhost }}
        - name: AMQP_EXCHANGE
          value: {{ .Values.amqpClient.exchange }}
        - name: AMQP_TOPIC
          value: {{ .Values.amqpClient.topic }}
        - name: AMQP_QUEUE
          value: {{ .Values.amqpClient.queue }}
        - name: AMQP_SEND_COUNT
          value: "{{ .Values.amqpClient.sendCount }}"
        - name: AMQP_RECEIVE_COUNT
          value: "{{ .Values.amqpClient.receiveCount }}"
        stdin: true
        tty: true
